# Generated by Django 4.0.4 on 2022-05-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_items', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Required',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_quantity', models.IntegerField()),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredients')),
                ('menu_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.menu_items')),
            ],
        ),
        migrations.AddField(
            model_name='menu_items',
            name='ingredients',
            field=models.ManyToManyField(through='ingredients.Stock_Required', to='ingredients.ingredients'),
        ),
    ]
