# Generated by Django 4.0.4 on 2022-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='menu_items',
            name='menu_item',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='menu_items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
