# Generated by Django 4.0.4 on 2022-05-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='menu_items',
            field=models.CharField(max_length=30, null=b'I01\n'),
        ),
    ]
