# Generated by Django 4.0.4 on 2022-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_menu_items_ingredients_menu_items_menu_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
