# Generated by Django 4.0.4 on 2022-05-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_menu_items_menu_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_items',
            old_name='menu_items',
            new_name='menu_item',
        ),
    ]
