# Generated by Django 4.0.4 on 2022-05-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_rename_menu_items_menu_items_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_required',
            name='ingredients_quantity',
            field=models.FloatField(null=True),
        ),
    ]
