# Generated by Django 4.0.4 on 2022-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_purchase_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
