# Generated by Django 4.0.4 on 2022-05-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_menu_items_date_purchased_purchase_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_history',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ingredients.menu_items'),
        ),
        migrations.AlterField(
            model_name='purchase_history',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_price', to='ingredients.menu_items'),
        ),
    ]
