# Generated by Django 4.0.4 on 2022-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_alter_purchase_history_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='date_purchased',
        ),
    ]
