# Generated by Django 4.0.4 on 2022-05-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_remove_menu_items_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_history',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_menu_item', to='ingredients.menu_items'),
        ),
    ]
