# Generated by Django 4.0.4 on 2022-05-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0014_alter_purchase_history_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_history',
            name='price',
        ),
        migrations.AlterField(
            model_name='purchase_history',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ingredients.menu_items'),
        ),
    ]
